"""Record every spoken line in the game with the Kokoro neural voice and write ../voice.js.

Usage: python3 make_voice.py <kokoro-model-dir> [cache-dir]

The model dir is the sherpa-onnx Kokoro export (model.int8.onnx, voices.bin, tokens.txt,
espeak-ng-data). Needs: pip install sherpa-onnx lameenc numpy, and node on PATH.
Clips are cached by text, so re-running only records lines that changed.
"""
import base64, hashlib, json, os, subprocess, sys

import lameenc
import numpy as np
import sherpa_onnx

VOICE_ID = 7        # bf_emma: British English, female
SPEED = 0.95
HERE = os.path.dirname(os.path.abspath(__file__))


def tts_engine(model_dir):
    kokoro = sherpa_onnx.OfflineTtsKokoroModelConfig(
        model=os.path.join(model_dir, 'model.int8.onnx'),
        voices=os.path.join(model_dir, 'voices.bin'),
        tokens=os.path.join(model_dir, 'tokens.txt'),
        data_dir=os.path.join(model_dir, 'espeak-ng-data'),
    )
    config = sherpa_onnx.OfflineTtsConfig(model=sherpa_onnx.OfflineTtsModelConfig(kokoro=kokoro, num_threads=4))
    return sherpa_onnx.OfflineTts(config)


def tidy(samples, rate):
    """Trim silence, normalise loudness and soften the edges."""
    s = np.asarray(samples, dtype=np.float32)
    loud = np.where(np.abs(s) > 0.01)[0]
    if len(loud):
        pad = int(rate * 0.04)
        s = s[max(0, loud[0] - pad): loud[-1] + pad]
    peak = float(np.abs(s).max()) or 1.0
    s = s * (0.9 / peak)
    fade = min(len(s) // 4, int(rate * 0.015))
    if fade:
        ramp = np.linspace(0, 1, fade, dtype=np.float32)
        s[:fade] *= ramp
        s[-fade:] *= ramp[::-1]
    return s


def to_mp3(samples, rate):
    enc = lameenc.Encoder()
    enc.set_bit_rate(48)
    enc.set_in_sample_rate(rate)
    enc.set_channels(1)
    enc.set_quality(2)
    pcm = (np.clip(samples, -1, 1) * 32767).astype(np.int16).tobytes()
    return enc.encode(pcm) + enc.flush()


def main():
    model_dir = sys.argv[1]
    cache = sys.argv[2] if len(sys.argv) > 2 else os.path.join(HERE, '.voice-cache')
    os.makedirs(cache, exist_ok=True)
    lines = json.loads(subprocess.check_output(['node', os.path.join(HERE, 'extract-lines.js')]))
    tts = None
    clips = {}
    for i, (key, text) in enumerate(sorted(lines.items())):
        name = hashlib.sha1(f'{VOICE_ID}|{SPEED}|{text}'.encode()).hexdigest() + '.mp3'
        path = os.path.join(cache, name)
        if not os.path.exists(path):
            tts = tts or tts_engine(model_dir)
            audio = tts.generate(text, sid=VOICE_ID, speed=SPEED)
            with open(path, 'wb') as f:
                f.write(to_mp3(tidy(audio.samples, audio.sample_rate), audio.sample_rate))
            print(f'[{i + 1}/{len(lines)}] {key}: {text}', flush=True)
        with open(path, 'rb') as f:
            clips[key] = base64.b64encode(f.read()).decode()
    out = os.path.join(HERE, '..', 'voice.js')
    with open(out, 'w') as f:
        f.write('// Generated by tools/make_voice.py: Kokoro neural voice (bf_emma), Apache-2.0.\n')
        f.write('window.LILY_VOICE = ' + json.dumps(clips, separators=(',', ':')) + ';\n')
    print(f'Wrote {len(clips)} clips, {os.path.getsize(out) // 1024} KB')


if __name__ == '__main__':
    main()
